name: Build my QMK configuration

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: ferris/sweep
          keymap: quiffco
          local-keymap-path: keymaps/quiffco
          output-dir: qmk-firmware-to-be-flashed

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: qmk-firmware-to-be-flashed
